### ISSUE TITLE
大规模使用授权问题

### ISSUE THREAD

**Issue by dysf888** [BertQiu/qiandao8#3]
作者能留个联系方式吗

**Comment by BertQiu** [comment]
本项目开源免费，可以clone下来自己定制化二次开发。本项目目前看来应该是不会再更新了。作者邮箱bert_qcg@aliyun.com

**Comment by dysf888** [comment]
> 本项目开源免费，可以clone下来自己定制化二次开发。本项目目前看来应该是不会再更新了。作者邮箱[bert_qcg@aliyun.com](mailto:bert_qcg@aliyun.com)

时隔一年肥肠感谢，正在学医的俺在空余时间学习了一波java，算是步入新手村了吧，目前完成了excal的导入，增加表预置名单左连接展示未到，待把代码整理 规范后 pr上来方便更多的人使用。
